### ISSUE TITLE
Crashing due to type error

### ISSUE THREAD

**Issue by lukewakeford** [chanomie/homebridge-connectedbytcp#6]
Just trying out HomeBridge to see if I can revive my old TCP bulbs. I've got a token setup but homebridge is now crashing when trying to setup the lights.

```
homebridge_1  | [1/29/2019, 10:25:12 PM] [ConnectedByTcp] roomGetCarousel result: <gip><version>1</version><rc>200</rc><room><rid>0</rid><name>Unassigned</name><desc></desc><known>1</known><type>0</type><color>000000</color><colorid>0</colorid><img>images/black.png</img><power>0</power><poweravg>0</poweravg><energy>0</energy><device><did>216733275353513085</did><known>1</known><lock>0</lock><state>1</state><level>100</level></device></room><room><rid>1</rid><name>Upstairs</name><desc></desc><known>1</known><type>0</type><color>00bd1f</color><colorid>1</colorid><img>images/green.png</img><power>0</power><poweravg>0</poweravg><energy>0</energy><device><did>216733275353513663</did><known>1</known><lock>0</lock><state>0</state><offline>1</offline></device><device><did>216733275353738881</did><known>1</known><lock>0</lock><state>0</state><offline>1</offline></device><device><did>216733275353511574</did><known>1</known><lock>0</lock><state>0</state><offline>1</offline></device></room><room><rid>4</rid><name>Downstairs </name><desc></desc><known>1</known><type>0</type><color>dde500</color><colorid>4</colorid><img>images/yellow.png</img><power>0</power><poweravg>0</poweravg><energy>0</energy><device><did>216733275353513932</did><known>1</known><lock>0</lock><state>0</state><offline>1</offline></device><device><did>216733275353525598</did><known>1</known><lock>0</lock><state>1</state><level>100</level></device><device><did>216733275353739930</did><known>1</known><lock>0</lock><state>0</state><offline>1</offline></device></room></gip>
homebridge_1  | [1/29/2019, 10:25:12 PM] [ConnectedByTcp] {"did":["216733275353513085"],"known":["1"],"lock":["0"],"state":["1"],"level":["100"]}
homebridge_1  | 
homebridge_1  | /homebridge/node_modules/homebridge-connectedbytcp/index.js:274
homebridge_1  |   if (connectedByTcp.deviceNames[deviceid]) {
homebridge_1  |                                 ^
homebridge_1  | TypeError: Cannot read property '216733275353513085' of undefined
homebridge_1  |     at new TcpLightbulb (/homebridge/node_modules/homebridge-connectedbytcp/index.js:274:33)
homebridge_1  |     at /homebridge/node_modules/homebridge-connectedbytcp/index.js:94:29
homebridge_1  |     at /homebridge/node_modules/homebridge-connectedbytcp/index.js:139:12
homebridge_1  |     at Parser.<anonymous> (/homebridge/node_modules/xml2js/lib/parser.js:303:18)
homebridge_1  |     at Parser.emit (events.js:182:13)
homebridge_1  |     at SAXParser.onclosetag (/homebridge/node_modules/xml2js/lib/parser.js:261:26)
homebridge_1  |     at emit (/homebridge/node_modules/sax/lib/sax.js:624:35)
homebridge_1  |     at emitNode (/homebridge/node_modules/sax/lib/sax.js:629:5)
homebridge_1  |     at closeTag (/homebridge/node_modules/sax/lib/sax.js:889:7)
homebridge_1  |     at SAXParser.write (/homebridge/node_modules/sax/lib/sax.js:1436:13)
homebridge_1  | -U /homebridge -P /homebridge/node_modules -C
```

Any help greatly appreciated. ✌️

**Comment by chanomie** [comment]
I think I see the bug, it's expecting a deviceNames in the config. I'll try and fix the code bug, but a work around should be putting an empty deviceName in your config like this:
```
       {
         "platform": "ConnectedByTcp",
         "name": "ConnectedByTcp",
         "ip": "192.168.7.40",
         "token": "xxx",
         "loglevel":"1",
         "deviceNames":{}
       }
```

**Comment by lukewakeford** [comment]
Thanks that worked 👍 - How come the device names are not pulled from the tcp gateway?

If you do take a look at the code it'd be nice to pull the device names in, save setting them up again 😄
